app:
  appName: "websocketServerCommunication"
  port: 8080
logs:
  file:
    logsDir: "./logs"
    maxSize: 10000000
    handleExceptions: true
    logstash: false
    timestamp: true
    showLevel: "debug"
    json: true
    maxFiles: 10
  console:
    handleExceptions: true
    timestamp: true
    colorize: true
    showLevel: "debug"
redis:
  serverHost: "1uakkf2d9303a.andrwel.koding.io"
  serverPort: 6379
taskManager:
  repeatDelay: 100